#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-lsmeans
Version  : 2.27.61
Release  : 5
URL      : https://cran.r-project.org/src/contrib/lsmeans_2.27-61.tar.gz
Source0  : https://cran.r-project.org/src/contrib/lsmeans_2.27-61.tar.gz
Summary  : Least-Squares Means
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-coda
Requires: R-estimability
Requires: R-multcomp
Requires: R-multcompView
Requires: R-mvtnorm
Requires: R-plyr
Requires: R-xtable
BuildRequires : R-coda
BuildRequires : R-estimability
BuildRequires : R-multcomp
BuildRequires : R-multcompView
BuildRequires : R-mvtnorm
BuildRequires : R-plyr
BuildRequires : R-xtable
BuildRequires : clr-R-helpers

%description
and mixed models. Compute contrasts or linear functions of 
    least-squares means, and comparisons of slopes. 
    Plots and compact letter displays. Least-squares means were proposed in
    Harvey, W (1960) "Least-squares analysis of data with unequal subclass numbers",
    Tech Report ARS-20-8, USDA National Agricultural Library, and discussed
    further in Searle, Speed, and Milliken (1980) "Population marginal means

%prep
%setup -q -c -n lsmeans

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523744894

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1523744894
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lsmeans
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lsmeans
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lsmeans
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library lsmeans|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lsmeans/CITATION
/usr/lib64/R/library/lsmeans/DESCRIPTION
/usr/lib64/R/library/lsmeans/INDEX
/usr/lib64/R/library/lsmeans/Meta/Rd.rds
/usr/lib64/R/library/lsmeans/Meta/data.rds
/usr/lib64/R/library/lsmeans/Meta/features.rds
/usr/lib64/R/library/lsmeans/Meta/hsearch.rds
/usr/lib64/R/library/lsmeans/Meta/links.rds
/usr/lib64/R/library/lsmeans/Meta/nsInfo.rds
/usr/lib64/R/library/lsmeans/Meta/package.rds
/usr/lib64/R/library/lsmeans/Meta/vignette.rds
/usr/lib64/R/library/lsmeans/NAMESPACE
/usr/lib64/R/library/lsmeans/NEWS
/usr/lib64/R/library/lsmeans/R/lsmeans
/usr/lib64/R/library/lsmeans/R/lsmeans.rdb
/usr/lib64/R/library/lsmeans/R/lsmeans.rdx
/usr/lib64/R/library/lsmeans/data/Rdata.rdb
/usr/lib64/R/library/lsmeans/data/Rdata.rds
/usr/lib64/R/library/lsmeans/data/Rdata.rdx
/usr/lib64/R/library/lsmeans/doc/index.html
/usr/lib64/R/library/lsmeans/doc/using-lsmeans.R
/usr/lib64/R/library/lsmeans/doc/using-lsmeans.pdf
/usr/lib64/R/library/lsmeans/doc/using-lsmeans.rnw
/usr/lib64/R/library/lsmeans/help/AnIndex
/usr/lib64/R/library/lsmeans/help/aliases.rds
/usr/lib64/R/library/lsmeans/help/lsmeans.rdb
/usr/lib64/R/library/lsmeans/help/lsmeans.rdx
/usr/lib64/R/library/lsmeans/help/paths.rds
/usr/lib64/R/library/lsmeans/html/00Index.html
/usr/lib64/R/library/lsmeans/html/R.css
